// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: misc/Containers.proto

package com.subterranean_security.crimson.core.proto.container;

public final class Containers {
  private Containers() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface KeyEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.subterranean_security.crimson.core.proto.container.KeyEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 date = 1;</code>
     */
    boolean hasDate();
    /**
     * <code>required int64 date = 1;</code>
     */
    long getDate();
  }
  /**
   * Protobuf type {@code com.subterranean_security.crimson.core.proto.container.KeyEntry}
   */
  public static final class KeyEntry extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.subterranean_security.crimson.core.proto.container.KeyEntry)
      KeyEntryOrBuilder {
    // Use KeyEntry.newBuilder() to construct.
    private KeyEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KeyEntry(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KeyEntry defaultInstance;
    public static KeyEntry getDefaultInstance() {
      return defaultInstance;
    }

    public KeyEntry getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private KeyEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              date_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.subterranean_security.crimson.core.proto.container.Containers.internal_static_com_subterranean_security_crimson_core_proto_container_KeyEntry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.subterranean_security.crimson.core.proto.container.Containers.internal_static_com_subterranean_security_crimson_core_proto_container_KeyEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry.class, com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry.Builder.class);
    }

    public static com.google.protobuf.Parser<KeyEntry> PARSER =
        new com.google.protobuf.AbstractParser<KeyEntry>() {
      public KeyEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KeyEntry(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<KeyEntry> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DATE_FIELD_NUMBER = 1;
    private long date_;
    /**
     * <code>required int64 date = 1;</code>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 date = 1;</code>
     */
    public long getDate() {
      return date_;
    }

    private void initFields() {
      date_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, date_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, date_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.subterranean_security.crimson.core.proto.container.KeyEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.subterranean_security.crimson.core.proto.container.KeyEntry)
        com.subterranean_security.crimson.core.proto.container.Containers.KeyEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.subterranean_security.crimson.core.proto.container.Containers.internal_static_com_subterranean_security_crimson_core_proto_container_KeyEntry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.subterranean_security.crimson.core.proto.container.Containers.internal_static_com_subterranean_security_crimson_core_proto_container_KeyEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry.class, com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry.Builder.class);
      }

      // Construct using com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        date_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.subterranean_security.crimson.core.proto.container.Containers.internal_static_com_subterranean_security_crimson_core_proto_container_KeyEntry_descriptor;
      }

      public com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry getDefaultInstanceForType() {
        return com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry.getDefaultInstance();
      }

      public com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry build() {
        com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry buildPartial() {
        com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry result = new com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.date_ = date_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry) {
          return mergeFrom((com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry other) {
        if (other == com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry.getDefaultInstance()) return this;
        if (other.hasDate()) {
          setDate(other.getDate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDate()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.subterranean_security.crimson.core.proto.container.Containers.KeyEntry) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long date_ ;
      /**
       * <code>required int64 date = 1;</code>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 date = 1;</code>
       */
      public long getDate() {
        return date_;
      }
      /**
       * <code>required int64 date = 1;</code>
       */
      public Builder setDate(long value) {
        bitField0_ |= 0x00000001;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 date = 1;</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000001);
        date_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.subterranean_security.crimson.core.proto.container.KeyEntry)
    }

    static {
      defaultInstance = new KeyEntry(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.subterranean_security.crimson.core.proto.container.KeyEntry)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subterranean_security_crimson_core_proto_container_KeyEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_subterranean_security_crimson_core_proto_container_KeyEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025misc/Containers.proto\0226com.subterranea" +
      "n_security.crimson.core.proto.container\"" +
      "\030\n\010KeyEntry\022\014\n\004date\030\001 \002(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_subterranean_security_crimson_core_proto_container_KeyEntry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_subterranean_security_crimson_core_proto_container_KeyEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_subterranean_security_crimson_core_proto_container_KeyEntry_descriptor,
        new java.lang.String[] { "Date", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
