/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_subterranean_security_crimson_core_util_Native */

#ifndef _Included_com_subterranean_security_crimson_core_util_Native
#define _Included_com_subterranean_security_crimson_core_util_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_subterranean_security_crimson_core_util_Native
 * Method:    getActiveWindow
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_subterranean_1security_crimson_core_util_Native_getActiveWindow
  (JNIEnv *, jclass);

/*
 * Class:     com_subterranean_security_crimson_core_util_Native
 * Method:    getSystemUptime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_subterranean_1security_crimson_core_util_Native_getSystemUptime
  (JNIEnv *, jclass);

/*
 * Class:     com_subterranean_security_crimson_core_util_Native
 * Method:    getCpuTemp
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_subterranean_1security_crimson_core_util_Native_getCpuTemp
  (JNIEnv *, jclass);

/*
 * Class:     com_subterranean_security_crimson_core_util_Native
 * Method:    poweroff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_subterranean_1security_crimson_core_util_Native_poweroff
  (JNIEnv *, jclass);

/*
 * Class:     com_subterranean_security_crimson_core_util_Native
 * Method:    restart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_subterranean_1security_crimson_core_util_Native_restart
  (JNIEnv *, jclass);

/*
 * Class:     com_subterranean_security_crimson_core_util_Native
 * Method:    standby
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_subterranean_1security_crimson_core_util_Native_standby
  (JNIEnv *, jclass);

/*
 * Class:     com_subterranean_security_crimson_core_util_Native
 * Method:    hibernate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_subterranean_1security_crimson_core_util_Native_hibernate
  (JNIEnv *, jclass);

/*
 * Class:     com_subterranean_security_crimson_core_util_Native
 * Method:    execute
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_subterranean_1security_crimson_core_util_Native_execute
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_subterranean_security_crimson_core_util_Native
 * Method:    startRD
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_subterranean_1security_crimson_core_util_Native_startRD
  (JNIEnv *, jclass);

/*
 * Class:     com_subterranean_security_crimson_core_util_Native
 * Method:    stopRD
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_subterranean_1security_crimson_core_util_Native_stopRD
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
