/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_subterranean_security_crimson_core_util_Native_Loader */

#ifndef _Included_com_subterranean_security_crimson_core_util_Native_Loader
#define _Included_com_subterranean_security_crimson_core_util_Native_Loader
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
