// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg/Service.proto

package com.subterranean_security.crimson.core.proto.msg;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Activation_RQOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.subterranean_security.crimson.core.proto.msg.Activation_RQ)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>required string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();
  }
  /**
   * Protobuf type {@code com.subterranean_security.crimson.core.proto.msg.Activation_RQ}
   */
  public static final class Activation_RQ extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.subterranean_security.crimson.core.proto.msg.Activation_RQ)
      Activation_RQOrBuilder {
    // Use Activation_RQ.newBuilder() to construct.
    private Activation_RQ(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Activation_RQ(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Activation_RQ defaultInstance;
    public static Activation_RQ getDefaultInstance() {
      return defaultInstance;
    }

    public Activation_RQ getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Activation_RQ(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              key_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.subterranean_security.crimson.core.proto.msg.Service.internal_static_com_subterranean_security_crimson_core_proto_msg_Activation_RQ_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.subterranean_security.crimson.core.proto.msg.Service.internal_static_com_subterranean_security_crimson_core_proto_msg_Activation_RQ_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ.class, com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ.Builder.class);
    }

    public static com.google.protobuf.Parser<Activation_RQ> PARSER =
        new com.google.protobuf.AbstractParser<Activation_RQ>() {
      public Activation_RQ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Activation_RQ(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Activation_RQ> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    /**
     * <code>required string key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      key_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.subterranean_security.crimson.core.proto.msg.Activation_RQ}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.subterranean_security.crimson.core.proto.msg.Activation_RQ)
        com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.subterranean_security.crimson.core.proto.msg.Service.internal_static_com_subterranean_security_crimson_core_proto_msg_Activation_RQ_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.subterranean_security.crimson.core.proto.msg.Service.internal_static_com_subterranean_security_crimson_core_proto_msg_Activation_RQ_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ.class, com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ.Builder.class);
      }

      // Construct using com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.subterranean_security.crimson.core.proto.msg.Service.internal_static_com_subterranean_security_crimson_core_proto_msg_Activation_RQ_descriptor;
      }

      public com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ getDefaultInstanceForType() {
        return com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ.getDefaultInstance();
      }

      public com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ build() {
        com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ buildPartial() {
        com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ result = new com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ) {
          return mergeFrom((com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ other) {
        if (other == com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.subterranean_security.crimson.core.proto.msg.Activation_RQ)
    }

    static {
      defaultInstance = new Activation_RQ(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.subterranean_security.crimson.core.proto.msg.Activation_RQ)
  }

  public interface Activation_RSOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.subterranean_security.crimson.core.proto.msg.Activation_RS)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bool result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>required bool result = 1;</code>
     */
    boolean getResult();

    /**
     * <code>optional string error = 2;</code>
     */
    boolean hasError();
    /**
     * <code>optional string error = 2;</code>
     */
    java.lang.String getError();
    /**
     * <code>optional string error = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrorBytes();
  }
  /**
   * Protobuf type {@code com.subterranean_security.crimson.core.proto.msg.Activation_RS}
   */
  public static final class Activation_RS extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.subterranean_security.crimson.core.proto.msg.Activation_RS)
      Activation_RSOrBuilder {
    // Use Activation_RS.newBuilder() to construct.
    private Activation_RS(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Activation_RS(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Activation_RS defaultInstance;
    public static Activation_RS getDefaultInstance() {
      return defaultInstance;
    }

    public Activation_RS getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Activation_RS(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readBool();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              error_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.subterranean_security.crimson.core.proto.msg.Service.internal_static_com_subterranean_security_crimson_core_proto_msg_Activation_RS_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.subterranean_security.crimson.core.proto.msg.Service.internal_static_com_subterranean_security_crimson_core_proto_msg_Activation_RS_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS.class, com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS.Builder.class);
    }

    public static com.google.protobuf.Parser<Activation_RS> PARSER =
        new com.google.protobuf.AbstractParser<Activation_RS>() {
      public Activation_RS parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Activation_RS(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Activation_RS> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESULT_FIELD_NUMBER = 1;
    private boolean result_;
    /**
     * <code>required bool result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool result = 1;</code>
     */
    public boolean getResult() {
      return result_;
    }

    public static final int ERROR_FIELD_NUMBER = 2;
    private java.lang.Object error_;
    /**
     * <code>optional string error = 2;</code>
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string error = 2;</code>
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          error_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string error = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      result_ = false;
      error_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getErrorBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getErrorBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.subterranean_security.crimson.core.proto.msg.Activation_RS}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.subterranean_security.crimson.core.proto.msg.Activation_RS)
        com.subterranean_security.crimson.core.proto.msg.Service.Activation_RSOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.subterranean_security.crimson.core.proto.msg.Service.internal_static_com_subterranean_security_crimson_core_proto_msg_Activation_RS_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.subterranean_security.crimson.core.proto.msg.Service.internal_static_com_subterranean_security_crimson_core_proto_msg_Activation_RS_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS.class, com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS.Builder.class);
      }

      // Construct using com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        error_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.subterranean_security.crimson.core.proto.msg.Service.internal_static_com_subterranean_security_crimson_core_proto_msg_Activation_RS_descriptor;
      }

      public com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS getDefaultInstanceForType() {
        return com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS.getDefaultInstance();
      }

      public com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS build() {
        com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS buildPartial() {
        com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS result = new com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.error_ = error_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS) {
          return mergeFrom((com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS other) {
        if (other == com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasError()) {
          bitField0_ |= 0x00000002;
          error_ = other.error_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean result_ ;
      /**
       * <code>required bool result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool result = 1;</code>
       */
      public boolean getResult() {
        return result_;
      }
      /**
       * <code>required bool result = 1;</code>
       */
      public Builder setResult(boolean value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool result = 1;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object error_ = "";
      /**
       * <code>optional string error = 2;</code>
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string error = 2;</code>
       */
      public java.lang.String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            error_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string error = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        java.lang.Object ref = error_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          error_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string error = 2;</code>
       */
      public Builder setError(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string error = 2;</code>
       */
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000002);
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      /**
       * <code>optional string error = 2;</code>
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        error_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.subterranean_security.crimson.core.proto.msg.Activation_RS)
    }

    static {
      defaultInstance = new Activation_RS(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.subterranean_security.crimson.core.proto.msg.Activation_RS)
  }

  public interface RetrieveKeys_RQOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RQ)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string user = 1;</code>
     */
    boolean hasUser();
    /**
     * <code>required string user = 1;</code>
     */
    java.lang.String getUser();
    /**
     * <code>required string user = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserBytes();

    /**
     * <code>required string password = 2;</code>
     */
    boolean hasPassword();
    /**
     * <code>required string password = 2;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>required string password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RQ}
   */
  public static final class RetrieveKeys_RQ extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RQ)
      RetrieveKeys_RQOrBuilder {
    // Use RetrieveKeys_RQ.newBuilder() to construct.
    private RetrieveKeys_RQ(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RetrieveKeys_RQ(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RetrieveKeys_RQ defaultInstance;
    public static RetrieveKeys_RQ getDefaultInstance() {
      return defaultInstance;
    }

    public RetrieveKeys_RQ getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RetrieveKeys_RQ(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              user_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              password_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.subterranean_security.crimson.core.proto.msg.Service.internal_static_com_subterranean_security_crimson_core_proto_msg_RetrieveKeys_RQ_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.subterranean_security.crimson.core.proto.msg.Service.internal_static_com_subterranean_security_crimson_core_proto_msg_RetrieveKeys_RQ_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ.class, com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ.Builder.class);
    }

    public static com.google.protobuf.Parser<RetrieveKeys_RQ> PARSER =
        new com.google.protobuf.AbstractParser<RetrieveKeys_RQ>() {
      public RetrieveKeys_RQ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RetrieveKeys_RQ(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RetrieveKeys_RQ> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int USER_FIELD_NUMBER = 1;
    private java.lang.Object user_;
    /**
     * <code>required string user = 1;</code>
     */
    public boolean hasUser() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string user = 1;</code>
     */
    public java.lang.String getUser() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          user_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string user = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserBytes() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        user_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private java.lang.Object password_;
    /**
     * <code>required string password = 2;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string password = 2;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      user_ = "";
      password_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUser()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswordBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswordBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RQ}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RQ)
        com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.subterranean_security.crimson.core.proto.msg.Service.internal_static_com_subterranean_security_crimson_core_proto_msg_RetrieveKeys_RQ_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.subterranean_security.crimson.core.proto.msg.Service.internal_static_com_subterranean_security_crimson_core_proto_msg_RetrieveKeys_RQ_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ.class, com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ.Builder.class);
      }

      // Construct using com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        user_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.subterranean_security.crimson.core.proto.msg.Service.internal_static_com_subterranean_security_crimson_core_proto_msg_RetrieveKeys_RQ_descriptor;
      }

      public com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ getDefaultInstanceForType() {
        return com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ.getDefaultInstance();
      }

      public com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ build() {
        com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ buildPartial() {
        com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ result = new com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.user_ = user_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ) {
          return mergeFrom((com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ other) {
        if (other == com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ.getDefaultInstance()) return this;
        if (other.hasUser()) {
          bitField0_ |= 0x00000001;
          user_ = other.user_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000002;
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUser()) {
          
          return false;
        }
        if (!hasPassword()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object user_ = "";
      /**
       * <code>required string user = 1;</code>
       */
      public boolean hasUser() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string user = 1;</code>
       */
      public java.lang.String getUser() {
        java.lang.Object ref = user_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            user_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string user = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserBytes() {
        java.lang.Object ref = user_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          user_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string user = 1;</code>
       */
      public Builder setUser(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        user_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string user = 1;</code>
       */
      public Builder clearUser() {
        bitField0_ = (bitField0_ & ~0x00000001);
        user_ = getDefaultInstance().getUser();
        onChanged();
        return this;
      }
      /**
       * <code>required string user = 1;</code>
       */
      public Builder setUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        user_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>required string password = 2;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string password = 2;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            password_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string password = 2;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RQ)
    }

    static {
      defaultInstance = new RetrieveKeys_RQ(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RQ)
  }

  public interface RetrieveKeys_RSOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RS)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string essential_keys = 1;</code>
     */
    com.google.protobuf.ProtocolStringList
        getEssentialKeysList();
    /**
     * <code>repeated string essential_keys = 1;</code>
     */
    int getEssentialKeysCount();
    /**
     * <code>repeated string essential_keys = 1;</code>
     */
    java.lang.String getEssentialKeys(int index);
    /**
     * <code>repeated string essential_keys = 1;</code>
     */
    com.google.protobuf.ByteString
        getEssentialKeysBytes(int index);

    /**
     * <code>repeated string business_keys = 2;</code>
     */
    com.google.protobuf.ProtocolStringList
        getBusinessKeysList();
    /**
     * <code>repeated string business_keys = 2;</code>
     */
    int getBusinessKeysCount();
    /**
     * <code>repeated string business_keys = 2;</code>
     */
    java.lang.String getBusinessKeys(int index);
    /**
     * <code>repeated string business_keys = 2;</code>
     */
    com.google.protobuf.ByteString
        getBusinessKeysBytes(int index);
  }
  /**
   * Protobuf type {@code com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RS}
   */
  public static final class RetrieveKeys_RS extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RS)
      RetrieveKeys_RSOrBuilder {
    // Use RetrieveKeys_RS.newBuilder() to construct.
    private RetrieveKeys_RS(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RetrieveKeys_RS(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RetrieveKeys_RS defaultInstance;
    public static RetrieveKeys_RS getDefaultInstance() {
      return defaultInstance;
    }

    public RetrieveKeys_RS getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RetrieveKeys_RS(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                essentialKeys_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              essentialKeys_.add(bs);
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                businessKeys_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              businessKeys_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          essentialKeys_ = essentialKeys_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          businessKeys_ = businessKeys_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.subterranean_security.crimson.core.proto.msg.Service.internal_static_com_subterranean_security_crimson_core_proto_msg_RetrieveKeys_RS_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.subterranean_security.crimson.core.proto.msg.Service.internal_static_com_subterranean_security_crimson_core_proto_msg_RetrieveKeys_RS_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS.class, com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS.Builder.class);
    }

    public static com.google.protobuf.Parser<RetrieveKeys_RS> PARSER =
        new com.google.protobuf.AbstractParser<RetrieveKeys_RS>() {
      public RetrieveKeys_RS parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RetrieveKeys_RS(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RetrieveKeys_RS> getParserForType() {
      return PARSER;
    }

    public static final int ESSENTIAL_KEYS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList essentialKeys_;
    /**
     * <code>repeated string essential_keys = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getEssentialKeysList() {
      return essentialKeys_;
    }
    /**
     * <code>repeated string essential_keys = 1;</code>
     */
    public int getEssentialKeysCount() {
      return essentialKeys_.size();
    }
    /**
     * <code>repeated string essential_keys = 1;</code>
     */
    public java.lang.String getEssentialKeys(int index) {
      return essentialKeys_.get(index);
    }
    /**
     * <code>repeated string essential_keys = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEssentialKeysBytes(int index) {
      return essentialKeys_.getByteString(index);
    }

    public static final int BUSINESS_KEYS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList businessKeys_;
    /**
     * <code>repeated string business_keys = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getBusinessKeysList() {
      return businessKeys_;
    }
    /**
     * <code>repeated string business_keys = 2;</code>
     */
    public int getBusinessKeysCount() {
      return businessKeys_.size();
    }
    /**
     * <code>repeated string business_keys = 2;</code>
     */
    public java.lang.String getBusinessKeys(int index) {
      return businessKeys_.get(index);
    }
    /**
     * <code>repeated string business_keys = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBusinessKeysBytes(int index) {
      return businessKeys_.getByteString(index);
    }

    private void initFields() {
      essentialKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      businessKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < essentialKeys_.size(); i++) {
        output.writeBytes(1, essentialKeys_.getByteString(i));
      }
      for (int i = 0; i < businessKeys_.size(); i++) {
        output.writeBytes(2, businessKeys_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < essentialKeys_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(essentialKeys_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getEssentialKeysList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < businessKeys_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(businessKeys_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getBusinessKeysList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RS}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RS)
        com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RSOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.subterranean_security.crimson.core.proto.msg.Service.internal_static_com_subterranean_security_crimson_core_proto_msg_RetrieveKeys_RS_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.subterranean_security.crimson.core.proto.msg.Service.internal_static_com_subterranean_security_crimson_core_proto_msg_RetrieveKeys_RS_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS.class, com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS.Builder.class);
      }

      // Construct using com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        essentialKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        businessKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.subterranean_security.crimson.core.proto.msg.Service.internal_static_com_subterranean_security_crimson_core_proto_msg_RetrieveKeys_RS_descriptor;
      }

      public com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS getDefaultInstanceForType() {
        return com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS.getDefaultInstance();
      }

      public com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS build() {
        com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS buildPartial() {
        com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS result = new com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          essentialKeys_ = essentialKeys_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.essentialKeys_ = essentialKeys_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          businessKeys_ = businessKeys_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.businessKeys_ = businessKeys_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS) {
          return mergeFrom((com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS other) {
        if (other == com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS.getDefaultInstance()) return this;
        if (!other.essentialKeys_.isEmpty()) {
          if (essentialKeys_.isEmpty()) {
            essentialKeys_ = other.essentialKeys_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEssentialKeysIsMutable();
            essentialKeys_.addAll(other.essentialKeys_);
          }
          onChanged();
        }
        if (!other.businessKeys_.isEmpty()) {
          if (businessKeys_.isEmpty()) {
            businessKeys_ = other.businessKeys_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureBusinessKeysIsMutable();
            businessKeys_.addAll(other.businessKeys_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList essentialKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureEssentialKeysIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          essentialKeys_ = new com.google.protobuf.LazyStringArrayList(essentialKeys_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string essential_keys = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getEssentialKeysList() {
        return essentialKeys_.getUnmodifiableView();
      }
      /**
       * <code>repeated string essential_keys = 1;</code>
       */
      public int getEssentialKeysCount() {
        return essentialKeys_.size();
      }
      /**
       * <code>repeated string essential_keys = 1;</code>
       */
      public java.lang.String getEssentialKeys(int index) {
        return essentialKeys_.get(index);
      }
      /**
       * <code>repeated string essential_keys = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEssentialKeysBytes(int index) {
        return essentialKeys_.getByteString(index);
      }
      /**
       * <code>repeated string essential_keys = 1;</code>
       */
      public Builder setEssentialKeys(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEssentialKeysIsMutable();
        essentialKeys_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string essential_keys = 1;</code>
       */
      public Builder addEssentialKeys(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEssentialKeysIsMutable();
        essentialKeys_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string essential_keys = 1;</code>
       */
      public Builder addAllEssentialKeys(
          java.lang.Iterable<java.lang.String> values) {
        ensureEssentialKeysIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, essentialKeys_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string essential_keys = 1;</code>
       */
      public Builder clearEssentialKeys() {
        essentialKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string essential_keys = 1;</code>
       */
      public Builder addEssentialKeysBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEssentialKeysIsMutable();
        essentialKeys_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList businessKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureBusinessKeysIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          businessKeys_ = new com.google.protobuf.LazyStringArrayList(businessKeys_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string business_keys = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getBusinessKeysList() {
        return businessKeys_.getUnmodifiableView();
      }
      /**
       * <code>repeated string business_keys = 2;</code>
       */
      public int getBusinessKeysCount() {
        return businessKeys_.size();
      }
      /**
       * <code>repeated string business_keys = 2;</code>
       */
      public java.lang.String getBusinessKeys(int index) {
        return businessKeys_.get(index);
      }
      /**
       * <code>repeated string business_keys = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBusinessKeysBytes(int index) {
        return businessKeys_.getByteString(index);
      }
      /**
       * <code>repeated string business_keys = 2;</code>
       */
      public Builder setBusinessKeys(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBusinessKeysIsMutable();
        businessKeys_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string business_keys = 2;</code>
       */
      public Builder addBusinessKeys(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBusinessKeysIsMutable();
        businessKeys_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string business_keys = 2;</code>
       */
      public Builder addAllBusinessKeys(
          java.lang.Iterable<java.lang.String> values) {
        ensureBusinessKeysIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, businessKeys_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string business_keys = 2;</code>
       */
      public Builder clearBusinessKeys() {
        businessKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string business_keys = 2;</code>
       */
      public Builder addBusinessKeysBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBusinessKeysIsMutable();
        businessKeys_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RS)
    }

    static {
      defaultInstance = new RetrieveKeys_RS(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RS)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subterranean_security_crimson_core_proto_msg_Activation_RQ_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_subterranean_security_crimson_core_proto_msg_Activation_RQ_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subterranean_security_crimson_core_proto_msg_Activation_RS_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_subterranean_security_crimson_core_proto_msg_Activation_RS_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subterranean_security_crimson_core_proto_msg_RetrieveKeys_RQ_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_subterranean_security_crimson_core_proto_msg_RetrieveKeys_RQ_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subterranean_security_crimson_core_proto_msg_RetrieveKeys_RS_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_subterranean_security_crimson_core_proto_msg_RetrieveKeys_RS_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021msg/Service.proto\0220com.subterranean_se" +
      "curity.crimson.core.proto.msg\"\034\n\rActivat" +
      "ion_RQ\022\013\n\003key\030\001 \002(\t\".\n\rActivation_RS\022\016\n\006" +
      "result\030\001 \002(\010\022\r\n\005error\030\002 \001(\t\"1\n\017RetrieveK" +
      "eys_RQ\022\014\n\004user\030\001 \002(\t\022\020\n\010password\030\002 \002(\t\"@" +
      "\n\017RetrieveKeys_RS\022\026\n\016essential_keys\030\001 \003(" +
      "\t\022\025\n\rbusiness_keys\030\002 \003(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_subterranean_security_crimson_core_proto_msg_Activation_RQ_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_subterranean_security_crimson_core_proto_msg_Activation_RQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_subterranean_security_crimson_core_proto_msg_Activation_RQ_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_com_subterranean_security_crimson_core_proto_msg_Activation_RS_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_subterranean_security_crimson_core_proto_msg_Activation_RS_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_subterranean_security_crimson_core_proto_msg_Activation_RS_descriptor,
        new java.lang.String[] { "Result", "Error", });
    internal_static_com_subterranean_security_crimson_core_proto_msg_RetrieveKeys_RQ_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_subterranean_security_crimson_core_proto_msg_RetrieveKeys_RQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_subterranean_security_crimson_core_proto_msg_RetrieveKeys_RQ_descriptor,
        new java.lang.String[] { "User", "Password", });
    internal_static_com_subterranean_security_crimson_core_proto_msg_RetrieveKeys_RS_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_subterranean_security_crimson_core_proto_msg_RetrieveKeys_RS_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_subterranean_security_crimson_core_proto_msg_RetrieveKeys_RS_descriptor,
        new java.lang.String[] { "EssentialKeys", "BusinessKeys", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
