// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg/SMSG.proto

package com.subterranean_security.crimson.core.proto.msg;

public final class SMSG {
  private SMSG() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.subterranean_security.crimson.core.proto.msg.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 2;</code>
     */
    int getId();

    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RQ activation_rq = 3;</code>
     *
     * <pre>
     *RQRS
     * </pre>
     */
    boolean hasActivationRq();
    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RQ activation_rq = 3;</code>
     *
     * <pre>
     *RQRS
     * </pre>
     */
    com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ getActivationRq();
    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RQ activation_rq = 3;</code>
     *
     * <pre>
     *RQRS
     * </pre>
     */
    com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQOrBuilder getActivationRqOrBuilder();

    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RS activation_rs = 4;</code>
     */
    boolean hasActivationRs();
    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RS activation_rs = 4;</code>
     */
    com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS getActivationRs();
    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RS activation_rs = 4;</code>
     */
    com.subterranean_security.crimson.core.proto.msg.Service.Activation_RSOrBuilder getActivationRsOrBuilder();

    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RQ retrieve_keys_rq = 5;</code>
     */
    boolean hasRetrieveKeysRq();
    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RQ retrieve_keys_rq = 5;</code>
     */
    com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ getRetrieveKeysRq();
    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RQ retrieve_keys_rq = 5;</code>
     */
    com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQOrBuilder getRetrieveKeysRqOrBuilder();

    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RS retrieve_keys_rs = 6;</code>
     */
    boolean hasRetrieveKeysRs();
    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RS retrieve_keys_rs = 6;</code>
     */
    com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS getRetrieveKeysRs();
    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RS retrieve_keys_rs = 6;</code>
     */
    com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RSOrBuilder getRetrieveKeysRsOrBuilder();

    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.Report_1W report_1w = 100;</code>
     *
     * <pre>
     *1W
     * </pre>
     */
    boolean hasReport1W();
    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.Report_1W report_1w = 100;</code>
     *
     * <pre>
     *1W
     * </pre>
     */
    com.subterranean_security.crimson.core.proto.msg.Reports.Report_1W getReport1W();
    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.Report_1W report_1w = 100;</code>
     *
     * <pre>
     *1W
     * </pre>
     */
    com.subterranean_security.crimson.core.proto.msg.Reports.Report_1WOrBuilder getReport1WOrBuilder();
  }
  /**
   * Protobuf type {@code com.subterranean_security.crimson.core.proto.msg.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.subterranean_security.crimson.core.proto.msg.Message)
      MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Message(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }

    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 26: {
              com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = activationRq_.toBuilder();
              }
              activationRq_ = input.readMessage(com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(activationRq_);
                activationRq_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 34: {
              com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = activationRs_.toBuilder();
              }
              activationRs_ = input.readMessage(com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(activationRs_);
                activationRs_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 42: {
              com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = retrieveKeysRq_.toBuilder();
              }
              retrieveKeysRq_ = input.readMessage(com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(retrieveKeysRq_);
                retrieveKeysRq_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 50: {
              com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = retrieveKeysRs_.toBuilder();
              }
              retrieveKeysRs_ = input.readMessage(com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(retrieveKeysRs_);
                retrieveKeysRs_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 802: {
              com.subterranean_security.crimson.core.proto.msg.Reports.Report_1W.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = report1W_.toBuilder();
              }
              report1W_ = input.readMessage(com.subterranean_security.crimson.core.proto.msg.Reports.Report_1W.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(report1W_);
                report1W_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.subterranean_security.crimson.core.proto.msg.SMSG.internal_static_com_subterranean_security_crimson_core_proto_msg_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.subterranean_security.crimson.core.proto.msg.SMSG.internal_static_com_subterranean_security_crimson_core_proto_msg_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.subterranean_security.crimson.core.proto.msg.SMSG.Message.class, com.subterranean_security.crimson.core.proto.msg.SMSG.Message.Builder.class);
    }

    public static com.google.protobuf.Parser<Message> PARSER =
        new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>optional int32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int ACTIVATION_RQ_FIELD_NUMBER = 3;
    private com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ activationRq_;
    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RQ activation_rq = 3;</code>
     *
     * <pre>
     *RQRS
     * </pre>
     */
    public boolean hasActivationRq() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RQ activation_rq = 3;</code>
     *
     * <pre>
     *RQRS
     * </pre>
     */
    public com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ getActivationRq() {
      return activationRq_;
    }
    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RQ activation_rq = 3;</code>
     *
     * <pre>
     *RQRS
     * </pre>
     */
    public com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQOrBuilder getActivationRqOrBuilder() {
      return activationRq_;
    }

    public static final int ACTIVATION_RS_FIELD_NUMBER = 4;
    private com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS activationRs_;
    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RS activation_rs = 4;</code>
     */
    public boolean hasActivationRs() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RS activation_rs = 4;</code>
     */
    public com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS getActivationRs() {
      return activationRs_;
    }
    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RS activation_rs = 4;</code>
     */
    public com.subterranean_security.crimson.core.proto.msg.Service.Activation_RSOrBuilder getActivationRsOrBuilder() {
      return activationRs_;
    }

    public static final int RETRIEVE_KEYS_RQ_FIELD_NUMBER = 5;
    private com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ retrieveKeysRq_;
    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RQ retrieve_keys_rq = 5;</code>
     */
    public boolean hasRetrieveKeysRq() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RQ retrieve_keys_rq = 5;</code>
     */
    public com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ getRetrieveKeysRq() {
      return retrieveKeysRq_;
    }
    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RQ retrieve_keys_rq = 5;</code>
     */
    public com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQOrBuilder getRetrieveKeysRqOrBuilder() {
      return retrieveKeysRq_;
    }

    public static final int RETRIEVE_KEYS_RS_FIELD_NUMBER = 6;
    private com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS retrieveKeysRs_;
    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RS retrieve_keys_rs = 6;</code>
     */
    public boolean hasRetrieveKeysRs() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RS retrieve_keys_rs = 6;</code>
     */
    public com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS getRetrieveKeysRs() {
      return retrieveKeysRs_;
    }
    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RS retrieve_keys_rs = 6;</code>
     */
    public com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RSOrBuilder getRetrieveKeysRsOrBuilder() {
      return retrieveKeysRs_;
    }

    public static final int REPORT_1W_FIELD_NUMBER = 100;
    private com.subterranean_security.crimson.core.proto.msg.Reports.Report_1W report1W_;
    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.Report_1W report_1w = 100;</code>
     *
     * <pre>
     *1W
     * </pre>
     */
    public boolean hasReport1W() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.Report_1W report_1w = 100;</code>
     *
     * <pre>
     *1W
     * </pre>
     */
    public com.subterranean_security.crimson.core.proto.msg.Reports.Report_1W getReport1W() {
      return report1W_;
    }
    /**
     * <code>optional .com.subterranean_security.crimson.core.proto.msg.Report_1W report_1w = 100;</code>
     *
     * <pre>
     *1W
     * </pre>
     */
    public com.subterranean_security.crimson.core.proto.msg.Reports.Report_1WOrBuilder getReport1WOrBuilder() {
      return report1W_;
    }

    private void initFields() {
      id_ = 0;
      activationRq_ = com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ.getDefaultInstance();
      activationRs_ = com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS.getDefaultInstance();
      retrieveKeysRq_ = com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ.getDefaultInstance();
      retrieveKeysRs_ = com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS.getDefaultInstance();
      report1W_ = com.subterranean_security.crimson.core.proto.msg.Reports.Report_1W.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasActivationRq()) {
        if (!getActivationRq().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasActivationRs()) {
        if (!getActivationRs().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasRetrieveKeysRq()) {
        if (!getRetrieveKeysRq().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasReport1W()) {
        if (!getReport1W().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(3, activationRq_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(4, activationRs_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(5, retrieveKeysRq_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(6, retrieveKeysRs_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(100, report1W_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, activationRq_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, activationRs_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, retrieveKeysRq_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, retrieveKeysRs_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(100, report1W_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.subterranean_security.crimson.core.proto.msg.SMSG.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.subterranean_security.crimson.core.proto.msg.SMSG.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.SMSG.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.subterranean_security.crimson.core.proto.msg.SMSG.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.SMSG.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.msg.SMSG.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.SMSG.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.msg.SMSG.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.SMSG.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.msg.SMSG.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.subterranean_security.crimson.core.proto.msg.SMSG.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.subterranean_security.crimson.core.proto.msg.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.subterranean_security.crimson.core.proto.msg.Message)
        com.subterranean_security.crimson.core.proto.msg.SMSG.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.subterranean_security.crimson.core.proto.msg.SMSG.internal_static_com_subterranean_security_crimson_core_proto_msg_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.subterranean_security.crimson.core.proto.msg.SMSG.internal_static_com_subterranean_security_crimson_core_proto_msg_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.subterranean_security.crimson.core.proto.msg.SMSG.Message.class, com.subterranean_security.crimson.core.proto.msg.SMSG.Message.Builder.class);
      }

      // Construct using com.subterranean_security.crimson.core.proto.msg.SMSG.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getActivationRqFieldBuilder();
          getActivationRsFieldBuilder();
          getRetrieveKeysRqFieldBuilder();
          getRetrieveKeysRsFieldBuilder();
          getReport1WFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (activationRqBuilder_ == null) {
          activationRq_ = com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ.getDefaultInstance();
        } else {
          activationRqBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (activationRsBuilder_ == null) {
          activationRs_ = com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS.getDefaultInstance();
        } else {
          activationRsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (retrieveKeysRqBuilder_ == null) {
          retrieveKeysRq_ = com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ.getDefaultInstance();
        } else {
          retrieveKeysRqBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (retrieveKeysRsBuilder_ == null) {
          retrieveKeysRs_ = com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS.getDefaultInstance();
        } else {
          retrieveKeysRsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        if (report1WBuilder_ == null) {
          report1W_ = com.subterranean_security.crimson.core.proto.msg.Reports.Report_1W.getDefaultInstance();
        } else {
          report1WBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.subterranean_security.crimson.core.proto.msg.SMSG.internal_static_com_subterranean_security_crimson_core_proto_msg_Message_descriptor;
      }

      public com.subterranean_security.crimson.core.proto.msg.SMSG.Message getDefaultInstanceForType() {
        return com.subterranean_security.crimson.core.proto.msg.SMSG.Message.getDefaultInstance();
      }

      public com.subterranean_security.crimson.core.proto.msg.SMSG.Message build() {
        com.subterranean_security.crimson.core.proto.msg.SMSG.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.subterranean_security.crimson.core.proto.msg.SMSG.Message buildPartial() {
        com.subterranean_security.crimson.core.proto.msg.SMSG.Message result = new com.subterranean_security.crimson.core.proto.msg.SMSG.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (activationRqBuilder_ == null) {
          result.activationRq_ = activationRq_;
        } else {
          result.activationRq_ = activationRqBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (activationRsBuilder_ == null) {
          result.activationRs_ = activationRs_;
        } else {
          result.activationRs_ = activationRsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (retrieveKeysRqBuilder_ == null) {
          result.retrieveKeysRq_ = retrieveKeysRq_;
        } else {
          result.retrieveKeysRq_ = retrieveKeysRqBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (retrieveKeysRsBuilder_ == null) {
          result.retrieveKeysRs_ = retrieveKeysRs_;
        } else {
          result.retrieveKeysRs_ = retrieveKeysRsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        if (report1WBuilder_ == null) {
          result.report1W_ = report1W_;
        } else {
          result.report1W_ = report1WBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.subterranean_security.crimson.core.proto.msg.SMSG.Message) {
          return mergeFrom((com.subterranean_security.crimson.core.proto.msg.SMSG.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.subterranean_security.crimson.core.proto.msg.SMSG.Message other) {
        if (other == com.subterranean_security.crimson.core.proto.msg.SMSG.Message.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasActivationRq()) {
          mergeActivationRq(other.getActivationRq());
        }
        if (other.hasActivationRs()) {
          mergeActivationRs(other.getActivationRs());
        }
        if (other.hasRetrieveKeysRq()) {
          mergeRetrieveKeysRq(other.getRetrieveKeysRq());
        }
        if (other.hasRetrieveKeysRs()) {
          mergeRetrieveKeysRs(other.getRetrieveKeysRs());
        }
        if (other.hasReport1W()) {
          mergeReport1W(other.getReport1W());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasActivationRq()) {
          if (!getActivationRq().isInitialized()) {
            
            return false;
          }
        }
        if (hasActivationRs()) {
          if (!getActivationRs().isInitialized()) {
            
            return false;
          }
        }
        if (hasRetrieveKeysRq()) {
          if (!getRetrieveKeysRq().isInitialized()) {
            
            return false;
          }
        }
        if (hasReport1W()) {
          if (!getReport1W().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.subterranean_security.crimson.core.proto.msg.SMSG.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.subterranean_security.crimson.core.proto.msg.SMSG.Message) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>optional int32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 2;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ activationRq_ = com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ, com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ.Builder, com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQOrBuilder> activationRqBuilder_;
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RQ activation_rq = 3;</code>
       *
       * <pre>
       *RQRS
       * </pre>
       */
      public boolean hasActivationRq() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RQ activation_rq = 3;</code>
       *
       * <pre>
       *RQRS
       * </pre>
       */
      public com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ getActivationRq() {
        if (activationRqBuilder_ == null) {
          return activationRq_;
        } else {
          return activationRqBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RQ activation_rq = 3;</code>
       *
       * <pre>
       *RQRS
       * </pre>
       */
      public Builder setActivationRq(com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ value) {
        if (activationRqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          activationRq_ = value;
          onChanged();
        } else {
          activationRqBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RQ activation_rq = 3;</code>
       *
       * <pre>
       *RQRS
       * </pre>
       */
      public Builder setActivationRq(
          com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ.Builder builderForValue) {
        if (activationRqBuilder_ == null) {
          activationRq_ = builderForValue.build();
          onChanged();
        } else {
          activationRqBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RQ activation_rq = 3;</code>
       *
       * <pre>
       *RQRS
       * </pre>
       */
      public Builder mergeActivationRq(com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ value) {
        if (activationRqBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              activationRq_ != com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ.getDefaultInstance()) {
            activationRq_ =
              com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ.newBuilder(activationRq_).mergeFrom(value).buildPartial();
          } else {
            activationRq_ = value;
          }
          onChanged();
        } else {
          activationRqBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RQ activation_rq = 3;</code>
       *
       * <pre>
       *RQRS
       * </pre>
       */
      public Builder clearActivationRq() {
        if (activationRqBuilder_ == null) {
          activationRq_ = com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ.getDefaultInstance();
          onChanged();
        } else {
          activationRqBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RQ activation_rq = 3;</code>
       *
       * <pre>
       *RQRS
       * </pre>
       */
      public com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ.Builder getActivationRqBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getActivationRqFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RQ activation_rq = 3;</code>
       *
       * <pre>
       *RQRS
       * </pre>
       */
      public com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQOrBuilder getActivationRqOrBuilder() {
        if (activationRqBuilder_ != null) {
          return activationRqBuilder_.getMessageOrBuilder();
        } else {
          return activationRq_;
        }
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RQ activation_rq = 3;</code>
       *
       * <pre>
       *RQRS
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ, com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ.Builder, com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQOrBuilder> 
          getActivationRqFieldBuilder() {
        if (activationRqBuilder_ == null) {
          activationRqBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ, com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQ.Builder, com.subterranean_security.crimson.core.proto.msg.Service.Activation_RQOrBuilder>(
                  getActivationRq(),
                  getParentForChildren(),
                  isClean());
          activationRq_ = null;
        }
        return activationRqBuilder_;
      }

      private com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS activationRs_ = com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS, com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS.Builder, com.subterranean_security.crimson.core.proto.msg.Service.Activation_RSOrBuilder> activationRsBuilder_;
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RS activation_rs = 4;</code>
       */
      public boolean hasActivationRs() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RS activation_rs = 4;</code>
       */
      public com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS getActivationRs() {
        if (activationRsBuilder_ == null) {
          return activationRs_;
        } else {
          return activationRsBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RS activation_rs = 4;</code>
       */
      public Builder setActivationRs(com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS value) {
        if (activationRsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          activationRs_ = value;
          onChanged();
        } else {
          activationRsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RS activation_rs = 4;</code>
       */
      public Builder setActivationRs(
          com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS.Builder builderForValue) {
        if (activationRsBuilder_ == null) {
          activationRs_ = builderForValue.build();
          onChanged();
        } else {
          activationRsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RS activation_rs = 4;</code>
       */
      public Builder mergeActivationRs(com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS value) {
        if (activationRsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              activationRs_ != com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS.getDefaultInstance()) {
            activationRs_ =
              com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS.newBuilder(activationRs_).mergeFrom(value).buildPartial();
          } else {
            activationRs_ = value;
          }
          onChanged();
        } else {
          activationRsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RS activation_rs = 4;</code>
       */
      public Builder clearActivationRs() {
        if (activationRsBuilder_ == null) {
          activationRs_ = com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS.getDefaultInstance();
          onChanged();
        } else {
          activationRsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RS activation_rs = 4;</code>
       */
      public com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS.Builder getActivationRsBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getActivationRsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RS activation_rs = 4;</code>
       */
      public com.subterranean_security.crimson.core.proto.msg.Service.Activation_RSOrBuilder getActivationRsOrBuilder() {
        if (activationRsBuilder_ != null) {
          return activationRsBuilder_.getMessageOrBuilder();
        } else {
          return activationRs_;
        }
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.Activation_RS activation_rs = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS, com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS.Builder, com.subterranean_security.crimson.core.proto.msg.Service.Activation_RSOrBuilder> 
          getActivationRsFieldBuilder() {
        if (activationRsBuilder_ == null) {
          activationRsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS, com.subterranean_security.crimson.core.proto.msg.Service.Activation_RS.Builder, com.subterranean_security.crimson.core.proto.msg.Service.Activation_RSOrBuilder>(
                  getActivationRs(),
                  getParentForChildren(),
                  isClean());
          activationRs_ = null;
        }
        return activationRsBuilder_;
      }

      private com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ retrieveKeysRq_ = com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ, com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ.Builder, com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQOrBuilder> retrieveKeysRqBuilder_;
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RQ retrieve_keys_rq = 5;</code>
       */
      public boolean hasRetrieveKeysRq() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RQ retrieve_keys_rq = 5;</code>
       */
      public com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ getRetrieveKeysRq() {
        if (retrieveKeysRqBuilder_ == null) {
          return retrieveKeysRq_;
        } else {
          return retrieveKeysRqBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RQ retrieve_keys_rq = 5;</code>
       */
      public Builder setRetrieveKeysRq(com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ value) {
        if (retrieveKeysRqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          retrieveKeysRq_ = value;
          onChanged();
        } else {
          retrieveKeysRqBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RQ retrieve_keys_rq = 5;</code>
       */
      public Builder setRetrieveKeysRq(
          com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ.Builder builderForValue) {
        if (retrieveKeysRqBuilder_ == null) {
          retrieveKeysRq_ = builderForValue.build();
          onChanged();
        } else {
          retrieveKeysRqBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RQ retrieve_keys_rq = 5;</code>
       */
      public Builder mergeRetrieveKeysRq(com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ value) {
        if (retrieveKeysRqBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              retrieveKeysRq_ != com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ.getDefaultInstance()) {
            retrieveKeysRq_ =
              com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ.newBuilder(retrieveKeysRq_).mergeFrom(value).buildPartial();
          } else {
            retrieveKeysRq_ = value;
          }
          onChanged();
        } else {
          retrieveKeysRqBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RQ retrieve_keys_rq = 5;</code>
       */
      public Builder clearRetrieveKeysRq() {
        if (retrieveKeysRqBuilder_ == null) {
          retrieveKeysRq_ = com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ.getDefaultInstance();
          onChanged();
        } else {
          retrieveKeysRqBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RQ retrieve_keys_rq = 5;</code>
       */
      public com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ.Builder getRetrieveKeysRqBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getRetrieveKeysRqFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RQ retrieve_keys_rq = 5;</code>
       */
      public com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQOrBuilder getRetrieveKeysRqOrBuilder() {
        if (retrieveKeysRqBuilder_ != null) {
          return retrieveKeysRqBuilder_.getMessageOrBuilder();
        } else {
          return retrieveKeysRq_;
        }
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RQ retrieve_keys_rq = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ, com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ.Builder, com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQOrBuilder> 
          getRetrieveKeysRqFieldBuilder() {
        if (retrieveKeysRqBuilder_ == null) {
          retrieveKeysRqBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ, com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQ.Builder, com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RQOrBuilder>(
                  getRetrieveKeysRq(),
                  getParentForChildren(),
                  isClean());
          retrieveKeysRq_ = null;
        }
        return retrieveKeysRqBuilder_;
      }

      private com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS retrieveKeysRs_ = com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS, com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS.Builder, com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RSOrBuilder> retrieveKeysRsBuilder_;
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RS retrieve_keys_rs = 6;</code>
       */
      public boolean hasRetrieveKeysRs() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RS retrieve_keys_rs = 6;</code>
       */
      public com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS getRetrieveKeysRs() {
        if (retrieveKeysRsBuilder_ == null) {
          return retrieveKeysRs_;
        } else {
          return retrieveKeysRsBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RS retrieve_keys_rs = 6;</code>
       */
      public Builder setRetrieveKeysRs(com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS value) {
        if (retrieveKeysRsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          retrieveKeysRs_ = value;
          onChanged();
        } else {
          retrieveKeysRsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RS retrieve_keys_rs = 6;</code>
       */
      public Builder setRetrieveKeysRs(
          com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS.Builder builderForValue) {
        if (retrieveKeysRsBuilder_ == null) {
          retrieveKeysRs_ = builderForValue.build();
          onChanged();
        } else {
          retrieveKeysRsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RS retrieve_keys_rs = 6;</code>
       */
      public Builder mergeRetrieveKeysRs(com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS value) {
        if (retrieveKeysRsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              retrieveKeysRs_ != com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS.getDefaultInstance()) {
            retrieveKeysRs_ =
              com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS.newBuilder(retrieveKeysRs_).mergeFrom(value).buildPartial();
          } else {
            retrieveKeysRs_ = value;
          }
          onChanged();
        } else {
          retrieveKeysRsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RS retrieve_keys_rs = 6;</code>
       */
      public Builder clearRetrieveKeysRs() {
        if (retrieveKeysRsBuilder_ == null) {
          retrieveKeysRs_ = com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS.getDefaultInstance();
          onChanged();
        } else {
          retrieveKeysRsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RS retrieve_keys_rs = 6;</code>
       */
      public com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS.Builder getRetrieveKeysRsBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getRetrieveKeysRsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RS retrieve_keys_rs = 6;</code>
       */
      public com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RSOrBuilder getRetrieveKeysRsOrBuilder() {
        if (retrieveKeysRsBuilder_ != null) {
          return retrieveKeysRsBuilder_.getMessageOrBuilder();
        } else {
          return retrieveKeysRs_;
        }
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.RetrieveKeys_RS retrieve_keys_rs = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS, com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS.Builder, com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RSOrBuilder> 
          getRetrieveKeysRsFieldBuilder() {
        if (retrieveKeysRsBuilder_ == null) {
          retrieveKeysRsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS, com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RS.Builder, com.subterranean_security.crimson.core.proto.msg.Service.RetrieveKeys_RSOrBuilder>(
                  getRetrieveKeysRs(),
                  getParentForChildren(),
                  isClean());
          retrieveKeysRs_ = null;
        }
        return retrieveKeysRsBuilder_;
      }

      private com.subterranean_security.crimson.core.proto.msg.Reports.Report_1W report1W_ = com.subterranean_security.crimson.core.proto.msg.Reports.Report_1W.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.subterranean_security.crimson.core.proto.msg.Reports.Report_1W, com.subterranean_security.crimson.core.proto.msg.Reports.Report_1W.Builder, com.subterranean_security.crimson.core.proto.msg.Reports.Report_1WOrBuilder> report1WBuilder_;
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.Report_1W report_1w = 100;</code>
       *
       * <pre>
       *1W
       * </pre>
       */
      public boolean hasReport1W() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.Report_1W report_1w = 100;</code>
       *
       * <pre>
       *1W
       * </pre>
       */
      public com.subterranean_security.crimson.core.proto.msg.Reports.Report_1W getReport1W() {
        if (report1WBuilder_ == null) {
          return report1W_;
        } else {
          return report1WBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.Report_1W report_1w = 100;</code>
       *
       * <pre>
       *1W
       * </pre>
       */
      public Builder setReport1W(com.subterranean_security.crimson.core.proto.msg.Reports.Report_1W value) {
        if (report1WBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          report1W_ = value;
          onChanged();
        } else {
          report1WBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.Report_1W report_1w = 100;</code>
       *
       * <pre>
       *1W
       * </pre>
       */
      public Builder setReport1W(
          com.subterranean_security.crimson.core.proto.msg.Reports.Report_1W.Builder builderForValue) {
        if (report1WBuilder_ == null) {
          report1W_ = builderForValue.build();
          onChanged();
        } else {
          report1WBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.Report_1W report_1w = 100;</code>
       *
       * <pre>
       *1W
       * </pre>
       */
      public Builder mergeReport1W(com.subterranean_security.crimson.core.proto.msg.Reports.Report_1W value) {
        if (report1WBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              report1W_ != com.subterranean_security.crimson.core.proto.msg.Reports.Report_1W.getDefaultInstance()) {
            report1W_ =
              com.subterranean_security.crimson.core.proto.msg.Reports.Report_1W.newBuilder(report1W_).mergeFrom(value).buildPartial();
          } else {
            report1W_ = value;
          }
          onChanged();
        } else {
          report1WBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.Report_1W report_1w = 100;</code>
       *
       * <pre>
       *1W
       * </pre>
       */
      public Builder clearReport1W() {
        if (report1WBuilder_ == null) {
          report1W_ = com.subterranean_security.crimson.core.proto.msg.Reports.Report_1W.getDefaultInstance();
          onChanged();
        } else {
          report1WBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.Report_1W report_1w = 100;</code>
       *
       * <pre>
       *1W
       * </pre>
       */
      public com.subterranean_security.crimson.core.proto.msg.Reports.Report_1W.Builder getReport1WBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getReport1WFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.Report_1W report_1w = 100;</code>
       *
       * <pre>
       *1W
       * </pre>
       */
      public com.subterranean_security.crimson.core.proto.msg.Reports.Report_1WOrBuilder getReport1WOrBuilder() {
        if (report1WBuilder_ != null) {
          return report1WBuilder_.getMessageOrBuilder();
        } else {
          return report1W_;
        }
      }
      /**
       * <code>optional .com.subterranean_security.crimson.core.proto.msg.Report_1W report_1w = 100;</code>
       *
       * <pre>
       *1W
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.subterranean_security.crimson.core.proto.msg.Reports.Report_1W, com.subterranean_security.crimson.core.proto.msg.Reports.Report_1W.Builder, com.subterranean_security.crimson.core.proto.msg.Reports.Report_1WOrBuilder> 
          getReport1WFieldBuilder() {
        if (report1WBuilder_ == null) {
          report1WBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.subterranean_security.crimson.core.proto.msg.Reports.Report_1W, com.subterranean_security.crimson.core.proto.msg.Reports.Report_1W.Builder, com.subterranean_security.crimson.core.proto.msg.Reports.Report_1WOrBuilder>(
                  getReport1W(),
                  getParentForChildren(),
                  isClean());
          report1W_ = null;
        }
        return report1WBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.subterranean_security.crimson.core.proto.msg.Message)
    }

    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.subterranean_security.crimson.core.proto.msg.Message)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subterranean_security_crimson_core_proto_msg_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_subterranean_security_crimson_core_proto_msg_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016msg/SMSG.proto\0220com.subterranean_secur" +
      "ity.crimson.core.proto.msg\032\021msg/Service." +
      "proto\032\021msg/Reports.proto\"\317\003\n\007Message\022\n\n\002" +
      "id\030\002 \001(\005\022V\n\ractivation_rq\030\003 \001(\0132?.com.su" +
      "bterranean_security.crimson.core.proto.m" +
      "sg.Activation_RQ\022V\n\ractivation_rs\030\004 \001(\0132" +
      "?.com.subterranean_security.crimson.core" +
      ".proto.msg.Activation_RS\022[\n\020retrieve_key" +
      "s_rq\030\005 \001(\0132A.com.subterranean_security.c" +
      "rimson.core.proto.msg.RetrieveKeys_RQ\022[\n",
      "\020retrieve_keys_rs\030\006 \001(\0132A.com.subterrane" +
      "an_security.crimson.core.proto.msg.Retri" +
      "eveKeys_RS\022N\n\treport_1w\030d \001(\0132;.com.subt" +
      "erranean_security.crimson.core.proto.msg" +
      ".Report_1W"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.subterranean_security.crimson.core.proto.msg.Service.getDescriptor(),
          com.subterranean_security.crimson.core.proto.msg.Reports.getDescriptor(),
        }, assigner);
    internal_static_com_subterranean_security_crimson_core_proto_msg_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_subterranean_security_crimson_core_proto_msg_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_subterranean_security_crimson_core_proto_msg_Message_descriptor,
        new java.lang.String[] { "Id", "ActivationRq", "ActivationRs", "RetrieveKeysRq", "RetrieveKeysRs", "Report1W", });
    com.subterranean_security.crimson.core.proto.msg.Service.getDescriptor();
    com.subterranean_security.crimson.core.proto.msg.Reports.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
