// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg/State.proto

package com.subterranean_security.crimson.core.proto.msg;

public final class State {
  private State() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.subterranean_security.crimson.core.proto.msg.STATES}
   */
  public enum STATES
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SERVER = 1;</code>
     */
    SERVER(0, 1),
    /**
     * <code>POWER = 2;</code>
     */
    POWER(1, 2),
    ;

    /**
     * <code>SERVER = 1;</code>
     */
    public static final int SERVER_VALUE = 1;
    /**
     * <code>POWER = 2;</code>
     */
    public static final int POWER_VALUE = 2;


    public final int getNumber() { return value; }

    public static STATES valueOf(int value) {
      switch (value) {
        case 1: return SERVER;
        case 2: return POWER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<STATES>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<STATES>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<STATES>() {
            public STATES findValueByNumber(int number) {
              return STATES.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.subterranean_security.crimson.core.proto.msg.State.getDescriptor().getEnumTypes().get(0);
    }

    private static final STATES[] VALUES = values();

    public static STATES valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private STATES(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.subterranean_security.crimson.core.proto.msg.STATES)
  }

  public interface StateChange_RQOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.subterranean_security.crimson.core.proto.msg.StateChange_RQ)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.subterranean_security.crimson.core.proto.msg.STATES type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .com.subterranean_security.crimson.core.proto.msg.STATES type = 1;</code>
     */
    com.subterranean_security.crimson.core.proto.msg.State.STATES getType();

    /**
     * <code>required bool change = 2;</code>
     */
    boolean hasChange();
    /**
     * <code>required bool change = 2;</code>
     */
    boolean getChange();

    /**
     * <code>optional int32 delay = 3;</code>
     */
    boolean hasDelay();
    /**
     * <code>optional int32 delay = 3;</code>
     */
    int getDelay();
  }
  /**
   * Protobuf type {@code com.subterranean_security.crimson.core.proto.msg.StateChange_RQ}
   */
  public static final class StateChange_RQ extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.subterranean_security.crimson.core.proto.msg.StateChange_RQ)
      StateChange_RQOrBuilder {
    // Use StateChange_RQ.newBuilder() to construct.
    private StateChange_RQ(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StateChange_RQ(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StateChange_RQ defaultInstance;
    public static StateChange_RQ getDefaultInstance() {
      return defaultInstance;
    }

    public StateChange_RQ getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StateChange_RQ(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.subterranean_security.crimson.core.proto.msg.State.STATES value = com.subterranean_security.crimson.core.proto.msg.State.STATES.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              change_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              delay_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.subterranean_security.crimson.core.proto.msg.State.internal_static_com_subterranean_security_crimson_core_proto_msg_StateChange_RQ_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.subterranean_security.crimson.core.proto.msg.State.internal_static_com_subterranean_security_crimson_core_proto_msg_StateChange_RQ_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ.class, com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ.Builder.class);
    }

    public static com.google.protobuf.Parser<StateChange_RQ> PARSER =
        new com.google.protobuf.AbstractParser<StateChange_RQ>() {
      public StateChange_RQ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StateChange_RQ(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StateChange_RQ> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.subterranean_security.crimson.core.proto.msg.State.STATES type_;
    /**
     * <code>required .com.subterranean_security.crimson.core.proto.msg.STATES type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.subterranean_security.crimson.core.proto.msg.STATES type = 1;</code>
     */
    public com.subterranean_security.crimson.core.proto.msg.State.STATES getType() {
      return type_;
    }

    public static final int CHANGE_FIELD_NUMBER = 2;
    private boolean change_;
    /**
     * <code>required bool change = 2;</code>
     */
    public boolean hasChange() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bool change = 2;</code>
     */
    public boolean getChange() {
      return change_;
    }

    public static final int DELAY_FIELD_NUMBER = 3;
    private int delay_;
    /**
     * <code>optional int32 delay = 3;</code>
     */
    public boolean hasDelay() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 delay = 3;</code>
     */
    public int getDelay() {
      return delay_;
    }

    private void initFields() {
      type_ = com.subterranean_security.crimson.core.proto.msg.State.STATES.SERVER;
      change_ = false;
      delay_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChange()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, change_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, delay_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, change_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, delay_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.subterranean_security.crimson.core.proto.msg.StateChange_RQ}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.subterranean_security.crimson.core.proto.msg.StateChange_RQ)
        com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.subterranean_security.crimson.core.proto.msg.State.internal_static_com_subterranean_security_crimson_core_proto_msg_StateChange_RQ_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.subterranean_security.crimson.core.proto.msg.State.internal_static_com_subterranean_security_crimson_core_proto_msg_StateChange_RQ_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ.class, com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ.Builder.class);
      }

      // Construct using com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.subterranean_security.crimson.core.proto.msg.State.STATES.SERVER;
        bitField0_ = (bitField0_ & ~0x00000001);
        change_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        delay_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.subterranean_security.crimson.core.proto.msg.State.internal_static_com_subterranean_security_crimson_core_proto_msg_StateChange_RQ_descriptor;
      }

      public com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ getDefaultInstanceForType() {
        return com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ.getDefaultInstance();
      }

      public com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ build() {
        com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ buildPartial() {
        com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ result = new com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.change_ = change_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.delay_ = delay_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ) {
          return mergeFrom((com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ other) {
        if (other == com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasChange()) {
          setChange(other.getChange());
        }
        if (other.hasDelay()) {
          setDelay(other.getDelay());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasChange()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.subterranean_security.crimson.core.proto.msg.State.StateChange_RQ) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.subterranean_security.crimson.core.proto.msg.State.STATES type_ = com.subterranean_security.crimson.core.proto.msg.State.STATES.SERVER;
      /**
       * <code>required .com.subterranean_security.crimson.core.proto.msg.STATES type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.subterranean_security.crimson.core.proto.msg.STATES type = 1;</code>
       */
      public com.subterranean_security.crimson.core.proto.msg.State.STATES getType() {
        return type_;
      }
      /**
       * <code>required .com.subterranean_security.crimson.core.proto.msg.STATES type = 1;</code>
       */
      public Builder setType(com.subterranean_security.crimson.core.proto.msg.State.STATES value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.subterranean_security.crimson.core.proto.msg.STATES type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.subterranean_security.crimson.core.proto.msg.State.STATES.SERVER;
        onChanged();
        return this;
      }

      private boolean change_ ;
      /**
       * <code>required bool change = 2;</code>
       */
      public boolean hasChange() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bool change = 2;</code>
       */
      public boolean getChange() {
        return change_;
      }
      /**
       * <code>required bool change = 2;</code>
       */
      public Builder setChange(boolean value) {
        bitField0_ |= 0x00000002;
        change_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool change = 2;</code>
       */
      public Builder clearChange() {
        bitField0_ = (bitField0_ & ~0x00000002);
        change_ = false;
        onChanged();
        return this;
      }

      private int delay_ ;
      /**
       * <code>optional int32 delay = 3;</code>
       */
      public boolean hasDelay() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 delay = 3;</code>
       */
      public int getDelay() {
        return delay_;
      }
      /**
       * <code>optional int32 delay = 3;</code>
       */
      public Builder setDelay(int value) {
        bitField0_ |= 0x00000004;
        delay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 delay = 3;</code>
       */
      public Builder clearDelay() {
        bitField0_ = (bitField0_ & ~0x00000004);
        delay_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.subterranean_security.crimson.core.proto.msg.StateChange_RQ)
    }

    static {
      defaultInstance = new StateChange_RQ(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.subterranean_security.crimson.core.proto.msg.StateChange_RQ)
  }

  public interface StateChange_RSOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.subterranean_security.crimson.core.proto.msg.StateChange_RS)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bool result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>required bool result = 1;</code>
     */
    boolean getResult();

    /**
     * <code>optional string comment = 2;</code>
     */
    boolean hasComment();
    /**
     * <code>optional string comment = 2;</code>
     */
    java.lang.String getComment();
    /**
     * <code>optional string comment = 2;</code>
     */
    com.google.protobuf.ByteString
        getCommentBytes();
  }
  /**
   * Protobuf type {@code com.subterranean_security.crimson.core.proto.msg.StateChange_RS}
   */
  public static final class StateChange_RS extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.subterranean_security.crimson.core.proto.msg.StateChange_RS)
      StateChange_RSOrBuilder {
    // Use StateChange_RS.newBuilder() to construct.
    private StateChange_RS(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StateChange_RS(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StateChange_RS defaultInstance;
    public static StateChange_RS getDefaultInstance() {
      return defaultInstance;
    }

    public StateChange_RS getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StateChange_RS(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readBool();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              comment_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.subterranean_security.crimson.core.proto.msg.State.internal_static_com_subterranean_security_crimson_core_proto_msg_StateChange_RS_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.subterranean_security.crimson.core.proto.msg.State.internal_static_com_subterranean_security_crimson_core_proto_msg_StateChange_RS_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS.class, com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS.Builder.class);
    }

    public static com.google.protobuf.Parser<StateChange_RS> PARSER =
        new com.google.protobuf.AbstractParser<StateChange_RS>() {
      public StateChange_RS parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StateChange_RS(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StateChange_RS> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESULT_FIELD_NUMBER = 1;
    private boolean result_;
    /**
     * <code>required bool result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool result = 1;</code>
     */
    public boolean getResult() {
      return result_;
    }

    public static final int COMMENT_FIELD_NUMBER = 2;
    private java.lang.Object comment_;
    /**
     * <code>optional string comment = 2;</code>
     */
    public boolean hasComment() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string comment = 2;</code>
     */
    public java.lang.String getComment() {
      java.lang.Object ref = comment_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          comment_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string comment = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCommentBytes() {
      java.lang.Object ref = comment_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      result_ = false;
      comment_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCommentBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCommentBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.subterranean_security.crimson.core.proto.msg.StateChange_RS}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.subterranean_security.crimson.core.proto.msg.StateChange_RS)
        com.subterranean_security.crimson.core.proto.msg.State.StateChange_RSOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.subterranean_security.crimson.core.proto.msg.State.internal_static_com_subterranean_security_crimson_core_proto_msg_StateChange_RS_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.subterranean_security.crimson.core.proto.msg.State.internal_static_com_subterranean_security_crimson_core_proto_msg_StateChange_RS_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS.class, com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS.Builder.class);
      }

      // Construct using com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        comment_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.subterranean_security.crimson.core.proto.msg.State.internal_static_com_subterranean_security_crimson_core_proto_msg_StateChange_RS_descriptor;
      }

      public com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS getDefaultInstanceForType() {
        return com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS.getDefaultInstance();
      }

      public com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS build() {
        com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS buildPartial() {
        com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS result = new com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.comment_ = comment_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS) {
          return mergeFrom((com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS other) {
        if (other == com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasComment()) {
          bitField0_ |= 0x00000002;
          comment_ = other.comment_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.subterranean_security.crimson.core.proto.msg.State.StateChange_RS) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean result_ ;
      /**
       * <code>required bool result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool result = 1;</code>
       */
      public boolean getResult() {
        return result_;
      }
      /**
       * <code>required bool result = 1;</code>
       */
      public Builder setResult(boolean value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool result = 1;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object comment_ = "";
      /**
       * <code>optional string comment = 2;</code>
       */
      public boolean hasComment() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string comment = 2;</code>
       */
      public java.lang.String getComment() {
        java.lang.Object ref = comment_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            comment_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string comment = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCommentBytes() {
        java.lang.Object ref = comment_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          comment_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string comment = 2;</code>
       */
      public Builder setComment(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        comment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string comment = 2;</code>
       */
      public Builder clearComment() {
        bitField0_ = (bitField0_ & ~0x00000002);
        comment_ = getDefaultInstance().getComment();
        onChanged();
        return this;
      }
      /**
       * <code>optional string comment = 2;</code>
       */
      public Builder setCommentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        comment_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.subterranean_security.crimson.core.proto.msg.StateChange_RS)
    }

    static {
      defaultInstance = new StateChange_RS(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.subterranean_security.crimson.core.proto.msg.StateChange_RS)
  }

  public interface GetState_RQOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.subterranean_security.crimson.core.proto.msg.GetState_RQ)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.subterranean_security.crimson.core.proto.msg.STATES type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .com.subterranean_security.crimson.core.proto.msg.STATES type = 1;</code>
     */
    com.subterranean_security.crimson.core.proto.msg.State.STATES getType();
  }
  /**
   * Protobuf type {@code com.subterranean_security.crimson.core.proto.msg.GetState_RQ}
   */
  public static final class GetState_RQ extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.subterranean_security.crimson.core.proto.msg.GetState_RQ)
      GetState_RQOrBuilder {
    // Use GetState_RQ.newBuilder() to construct.
    private GetState_RQ(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetState_RQ(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetState_RQ defaultInstance;
    public static GetState_RQ getDefaultInstance() {
      return defaultInstance;
    }

    public GetState_RQ getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetState_RQ(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.subterranean_security.crimson.core.proto.msg.State.STATES value = com.subterranean_security.crimson.core.proto.msg.State.STATES.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.subterranean_security.crimson.core.proto.msg.State.internal_static_com_subterranean_security_crimson_core_proto_msg_GetState_RQ_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.subterranean_security.crimson.core.proto.msg.State.internal_static_com_subterranean_security_crimson_core_proto_msg_GetState_RQ_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ.class, com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ.Builder.class);
    }

    public static com.google.protobuf.Parser<GetState_RQ> PARSER =
        new com.google.protobuf.AbstractParser<GetState_RQ>() {
      public GetState_RQ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetState_RQ(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetState_RQ> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.subterranean_security.crimson.core.proto.msg.State.STATES type_;
    /**
     * <code>required .com.subterranean_security.crimson.core.proto.msg.STATES type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.subterranean_security.crimson.core.proto.msg.STATES type = 1;</code>
     */
    public com.subterranean_security.crimson.core.proto.msg.State.STATES getType() {
      return type_;
    }

    private void initFields() {
      type_ = com.subterranean_security.crimson.core.proto.msg.State.STATES.SERVER;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.subterranean_security.crimson.core.proto.msg.GetState_RQ}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.subterranean_security.crimson.core.proto.msg.GetState_RQ)
        com.subterranean_security.crimson.core.proto.msg.State.GetState_RQOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.subterranean_security.crimson.core.proto.msg.State.internal_static_com_subterranean_security_crimson_core_proto_msg_GetState_RQ_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.subterranean_security.crimson.core.proto.msg.State.internal_static_com_subterranean_security_crimson_core_proto_msg_GetState_RQ_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ.class, com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ.Builder.class);
      }

      // Construct using com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.subterranean_security.crimson.core.proto.msg.State.STATES.SERVER;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.subterranean_security.crimson.core.proto.msg.State.internal_static_com_subterranean_security_crimson_core_proto_msg_GetState_RQ_descriptor;
      }

      public com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ getDefaultInstanceForType() {
        return com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ.getDefaultInstance();
      }

      public com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ build() {
        com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ buildPartial() {
        com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ result = new com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ) {
          return mergeFrom((com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ other) {
        if (other == com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.subterranean_security.crimson.core.proto.msg.State.GetState_RQ) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.subterranean_security.crimson.core.proto.msg.State.STATES type_ = com.subterranean_security.crimson.core.proto.msg.State.STATES.SERVER;
      /**
       * <code>required .com.subterranean_security.crimson.core.proto.msg.STATES type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.subterranean_security.crimson.core.proto.msg.STATES type = 1;</code>
       */
      public com.subterranean_security.crimson.core.proto.msg.State.STATES getType() {
        return type_;
      }
      /**
       * <code>required .com.subterranean_security.crimson.core.proto.msg.STATES type = 1;</code>
       */
      public Builder setType(com.subterranean_security.crimson.core.proto.msg.State.STATES value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.subterranean_security.crimson.core.proto.msg.STATES type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.subterranean_security.crimson.core.proto.msg.State.STATES.SERVER;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.subterranean_security.crimson.core.proto.msg.GetState_RQ)
    }

    static {
      defaultInstance = new GetState_RQ(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.subterranean_security.crimson.core.proto.msg.GetState_RQ)
  }

  public interface GetState_RSOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.subterranean_security.crimson.core.proto.msg.GetState_RS)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.subterranean_security.crimson.core.proto.msg.GetState_RS}
   */
  public static final class GetState_RS extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.subterranean_security.crimson.core.proto.msg.GetState_RS)
      GetState_RSOrBuilder {
    // Use GetState_RS.newBuilder() to construct.
    private GetState_RS(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetState_RS(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetState_RS defaultInstance;
    public static GetState_RS getDefaultInstance() {
      return defaultInstance;
    }

    public GetState_RS getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetState_RS(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.subterranean_security.crimson.core.proto.msg.State.internal_static_com_subterranean_security_crimson_core_proto_msg_GetState_RS_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.subterranean_security.crimson.core.proto.msg.State.internal_static_com_subterranean_security_crimson_core_proto_msg_GetState_RS_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.subterranean_security.crimson.core.proto.msg.State.GetState_RS.class, com.subterranean_security.crimson.core.proto.msg.State.GetState_RS.Builder.class);
    }

    public static com.google.protobuf.Parser<GetState_RS> PARSER =
        new com.google.protobuf.AbstractParser<GetState_RS>() {
      public GetState_RS parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetState_RS(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetState_RS> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.subterranean_security.crimson.core.proto.msg.State.GetState_RS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.GetState_RS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.GetState_RS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.GetState_RS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.GetState_RS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.GetState_RS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.GetState_RS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.GetState_RS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.GetState_RS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.subterranean_security.crimson.core.proto.msg.State.GetState_RS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.subterranean_security.crimson.core.proto.msg.State.GetState_RS prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.subterranean_security.crimson.core.proto.msg.GetState_RS}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.subterranean_security.crimson.core.proto.msg.GetState_RS)
        com.subterranean_security.crimson.core.proto.msg.State.GetState_RSOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.subterranean_security.crimson.core.proto.msg.State.internal_static_com_subterranean_security_crimson_core_proto_msg_GetState_RS_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.subterranean_security.crimson.core.proto.msg.State.internal_static_com_subterranean_security_crimson_core_proto_msg_GetState_RS_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.subterranean_security.crimson.core.proto.msg.State.GetState_RS.class, com.subterranean_security.crimson.core.proto.msg.State.GetState_RS.Builder.class);
      }

      // Construct using com.subterranean_security.crimson.core.proto.msg.State.GetState_RS.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.subterranean_security.crimson.core.proto.msg.State.internal_static_com_subterranean_security_crimson_core_proto_msg_GetState_RS_descriptor;
      }

      public com.subterranean_security.crimson.core.proto.msg.State.GetState_RS getDefaultInstanceForType() {
        return com.subterranean_security.crimson.core.proto.msg.State.GetState_RS.getDefaultInstance();
      }

      public com.subterranean_security.crimson.core.proto.msg.State.GetState_RS build() {
        com.subterranean_security.crimson.core.proto.msg.State.GetState_RS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.subterranean_security.crimson.core.proto.msg.State.GetState_RS buildPartial() {
        com.subterranean_security.crimson.core.proto.msg.State.GetState_RS result = new com.subterranean_security.crimson.core.proto.msg.State.GetState_RS(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.subterranean_security.crimson.core.proto.msg.State.GetState_RS) {
          return mergeFrom((com.subterranean_security.crimson.core.proto.msg.State.GetState_RS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.subterranean_security.crimson.core.proto.msg.State.GetState_RS other) {
        if (other == com.subterranean_security.crimson.core.proto.msg.State.GetState_RS.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.subterranean_security.crimson.core.proto.msg.State.GetState_RS parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.subterranean_security.crimson.core.proto.msg.State.GetState_RS) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.subterranean_security.crimson.core.proto.msg.GetState_RS)
    }

    static {
      defaultInstance = new GetState_RS(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.subterranean_security.crimson.core.proto.msg.GetState_RS)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subterranean_security_crimson_core_proto_msg_StateChange_RQ_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_subterranean_security_crimson_core_proto_msg_StateChange_RQ_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subterranean_security_crimson_core_proto_msg_StateChange_RS_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_subterranean_security_crimson_core_proto_msg_StateChange_RS_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subterranean_security_crimson_core_proto_msg_GetState_RQ_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_subterranean_security_crimson_core_proto_msg_GetState_RQ_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subterranean_security_crimson_core_proto_msg_GetState_RS_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_subterranean_security_crimson_core_proto_msg_GetState_RS_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017msg/State.proto\0220com.subterranean_secu" +
      "rity.crimson.core.proto.msg\"w\n\016StateChan" +
      "ge_RQ\022F\n\004type\030\001 \002(\01628.com.subterranean_s" +
      "ecurity.crimson.core.proto.msg.STATES\022\016\n" +
      "\006change\030\002 \002(\010\022\r\n\005delay\030\003 \001(\005\"1\n\016StateCha" +
      "nge_RS\022\016\n\006result\030\001 \002(\010\022\017\n\007comment\030\002 \001(\t\"" +
      "U\n\013GetState_RQ\022F\n\004type\030\001 \002(\01628.com.subte" +
      "rranean_security.crimson.core.proto.msg." +
      "STATES\"\r\n\013GetState_RS*\037\n\006STATES\022\n\n\006SERVE" +
      "R\020\001\022\t\n\005POWER\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_subterranean_security_crimson_core_proto_msg_StateChange_RQ_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_subterranean_security_crimson_core_proto_msg_StateChange_RQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_subterranean_security_crimson_core_proto_msg_StateChange_RQ_descriptor,
        new java.lang.String[] { "Type", "Change", "Delay", });
    internal_static_com_subterranean_security_crimson_core_proto_msg_StateChange_RS_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_subterranean_security_crimson_core_proto_msg_StateChange_RS_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_subterranean_security_crimson_core_proto_msg_StateChange_RS_descriptor,
        new java.lang.String[] { "Result", "Comment", });
    internal_static_com_subterranean_security_crimson_core_proto_msg_GetState_RQ_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_subterranean_security_crimson_core_proto_msg_GetState_RQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_subterranean_security_crimson_core_proto_msg_GetState_RQ_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_com_subterranean_security_crimson_core_proto_msg_GetState_RS_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_subterranean_security_crimson_core_proto_msg_GetState_RS_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_subterranean_security_crimson_core_proto_msg_GetState_RS_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
